name: Kobo to Firebase Sync

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
          KOBO_API_KEY: ${{ secrets.KOBO_API_KEY }}
          KOBO_ECDCNETWORK_UID: ${{ secrets.KOBO_ECDCNETWORK_UID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Run Sync
        run: node sync_data.js